name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0

    - name: Install dependencies
      run: dotnet restore

    - name: Build Blazor App
      run: dotnet publish -c Release -o ./bin/Release/net9.0/publish

    - name: List files in publish directory
      run: ls -R ./bin/Release/net9.0/publish/wwwroot

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./bin/Release/net9.0/publish/wwwroot

    - name: Set up Git user
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Force update of the deployment
      run: git commit --allow-empty -m "Force GitHub Pages update"
